[package]
authors = ["Kun Lai <laikun@linux.alibaba.com>"]
default-run = "cryptpilot"
description = "A utility for protecting data at rest in confidential environment"
edition = "2021"
name = "cryptpilot"
version = "0.1.0"

[dependencies]
again = "0.1.2"
anyhow = "1.0.81"
async-trait = "0.1.83"
base64 = "0.22.1"
clap = {version = "4.5.4", features = ["derive"]}
comfy-table = "7.1.1"
dialoguer = "0.11.0"
documented = "0.9.1"
hex = "0.4.3"
kms = {git = "https://github.com/confidential-containers/guest-components.git", tag = "v0.10.0", optional = true, default-features = false, features = ["aliyun"]}
lazy_static = "1.5.0"
libc = "0.2.161"
log = "0.4.20"
protobuf = {version = "~3.4.0", optional = true}
rand = {version = "0.8.5", features = ["std_rng"]}
reqwest = {version = "0.12.9", default-features = false, features = ["rustls-tls"]}
run_script = "0.11.0"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0.134"
serde_variant = "0.1.3"
sha2 = {version = "0.10.8"}
shadow-rs = "0.35.2"
tempfile = "3.10.1"
tokio = {version = "1.41.0", features = ["rt", "macros", "signal", "rt-multi-thread", "sync", "fs", "net", "io-util", "process"]}
toml = "0.8.19"
toml_edit = {version = "0.22.22", features = ["serde"]}
tracing = "0.1.41"
tracing-log = "0.2.0"
tracing-subscriber = "0.3.19"
ttrpc = {version = "0.8.0", default-features = false, features = ["async"], optional = true}
zeroize = {version = "1.8.1", features = ["zeroize_derive"]}

[build-dependencies]
shadow-rs = "0.35.2"
ttrpc-codegen = {version = "0.4.2", optional = true}

[features]
default = ["provider-kbs", "provider-kms", "provider-otp", "provider-tpm2"]
provider-kbs = [
  "dep:ttrpc-codegen",
  "dep:ttrpc",
  "dep:protobuf",
]
provider-kms = ["dep:kms"]
provider-otp = []
provider-tpm2 = []
