volume = "data4"
dev = "/dev/nvme1n1p5"
auto_open = true
makefs = "ext4"
integrity = true

[encrypt.kbs]
kbs_url = "https://1.2.3.4:8080"
key_uri = "kbs:///default/mykey/volume_data0"
kbs_root_cert = """
-----BEGIN CERTIFICATE-----
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
-----END CERTIFICATE-----
"""
