name: Build RPM Package

on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Check pre-release
      run: |
        tag="${GITHUB_REF#refs/*/}"
        echo "tag=tag"
        if [[ ${tag} == *alpha* || ${tag} == *beta* ]]
        then
            prerelease=true
        else
            prerelease=false
        fi
        echo "prerelease=$prerelease"
        echo "PRE_RELEASE=$prerelease" >> $GITHUB_ENV

    - uses: dtolnay/rust-toolchain@1.75.0

    - name: Build RPM package
      run: |
        make create-tarball
        make rpm-build-in-docker
        mkdir -p $GITHUB_WORKSPACE/rpmbuild
        cp -r ~/rpmbuild/SRPMS/ $GITHUB_WORKSPACE/rpmbuild/
        cp -r ~/rpmbuild/RPMS/ $GITHUB_WORKSPACE/rpmbuild/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: rpm-packages
        if-no-files-found: error
        path: |
          ./rpmbuild/SRPMS/*.src.rpm
          ./rpmbuild/RPMS/*/*.rpm

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        fail_on_unmatched_files: true
        prerelease: ${{ env.PRE_RELEASE }}
        files: |
          /tmp/cryptpilot-*.src.tar.gz
          ./rpmbuild/SRPMS/*.src.rpm
          ./rpmbuild/RPMS/*/*.rpm
